backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    folder: "src/pages" # The path to the folder where the documents are stored
    media_folder: "src/assets/images" # Location where files will be stored in the repo
    public_folder: "src/assets/images" # The src attribute for uploaded media
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
